/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Testing_Land1;

import java.util.LinkedList;
import java.util.List;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    //public App(String name, String Kategorie);
    String name;
    String Kategorie;

    public App(String name, String Kategorie){
        this.name = name;
        this.Kategorie = Kategorie;
    }

    public static void main(String[] args) {
        System.out.println(new App("test", "lul").getGreeting());

        List<App> applist = new LinkedList<App>();
        App app1 = new App("Spiel1", "Spiel");
        applist.add(app1);
        System.out.println(applist);
    }
}
